### ISSUE TITLE
Problem with the tags versions

### ISSUE THREAD

**Issue by mapirelli** [JBZoo/Image#1]
Hi,

this porting is very usefull, i love the new methods, but i found that the tag version 3.0.* released differs from the master and the documentation. 
I downloaded the library with composer
Mariano

**Comment by SmetDenis** [comment]
Hi Mariano,

Thanks a lot!

Yes stable tag is not released yet, because I'm develop it now.
But you can download dev version via composer.
```sh
composer require jbzoo/image:"3.x-dev"
```
Best regards, Denis.

**Comment by mapirelli** [comment]
Hi Denis,
i understand, thanks.

i report you a little writing mistake on line 331 in the dev version:
`$cleanFilename = FS::clean($filename);
        if (!file_exists($cleanFilename)) {
            throw new Exception('Image file not forund: ' . $filename);
        }`

And then i want suggest you to develop a feature that can be usefull:
The possibility to load an image from string and not only from a file, this can be usefull when we want manipulate images loaded from database. Now i extended your class and i overload the constructor to do so and i want share with you this few lines of code:

`public function __construct($imageString) {
		
		// Require GD library
		if (!extension_loaded('gd')) {
			throw new \Exception('Required extension GD is not loaded.');
		}
		
		if (empty($imageString)) {
			throw new \Exception('Empty image string data');
		}

		if (function_exists('getimagesizefromstring')) {
			//gather meta data
			$info = getimagesizefromstring($imageString);
		} else {
			throw new \Exception('PHP 5.4 is required to use method getimagesizefromstring');
		}

		$this->cleanup();
		$this->_mime   = $info['mime'];
		$this->_width  = $info[0];
		$this->_height = $info[1];
		$this->_image = imagecreatefromstring($imageString);
		$this->_exif   = array();
		$this->_orient = $this->_getOrientation();

		imagesavealpha($this->_image, true);
		imagealphablending($this->_image, true);

		return $this;
	}`

Thanks for the work.
Best regards
Mariano

**Comment by SmetDenis** [comment]
Yea, thanks.
I think it can be usefull, I added support to new release.

But I think that saving images to database is nt good idea.

**Comment by mapirelli** [comment]
I forgot to add the method getImageData()

`/**
	 * Outputs image as data base64 to use as img src
	 *
	 * @param null|string $format  If omitted or null - format of original file will be used, may be gif|jpg|png
	 * @param int|null    $quality Output image quality in percents 0-100
	 * @return string
	 *
	 * @throws \Exception
	 */
	public function getImageData($format = 'png', $quality = null)
	{
		if (!$this->_image) {
			throw new \Exception('Image resource not defined');
		}
		// Output the image
		ob_start();
		$mimetype  = $this->_renderImageByFormat($format, null, $quality);
		$imageData = ob_get_contents();
		ob_end_clean();

		return $imageData;
	}`

**Comment by SmetDenis** [comment]
Great!

PS I changed your comments, fixed highlight of code.

**Comment by mapirelli** [comment]
Thank you very much.

I want suggest you just another thing. i hope that this can help:

I found that PHP under windows use the extension .tmp on uploaded files, included images, while others system don't use the extension.

So if i use a code like this an exception will be thrown:

```php
$image = new Image($_FILES['name']['tmp_name']); // the temp file
$image->bestFit(800, 600)->save();` //save the temp file
copy($_FILES['name']['tmp_name'], $newPath) //copy the file 
```

the exception is: Undefined format. because the format is tmp.

```php
    protected function _renderImageByFormat($format, $filename, $quality)
    {
        if (Helper::isJpeg($format)) {
        } elseif (Helper::isPng($format)) {
        } elseif (Helper::isGif($format)) {
        } else {
            throw new Exception('Undefined format: ' . $format);
        }
        return $result;
    }
 ```

so i suggest this behavior: 

when the method save() is called, could be better read the image format from the mime type instead from file extension, the filename is not changed so also the format, and the error above will be prevented.

while on savaAs(), read like now the format from the file name extension.

i hope that is comprensible what i wrote.

Mariano

**Comment by SmetDenis** [comment]
Hi Mariano,

I jsut pushed new version to `3.x-dev`. Please try it and tell me what do you think.

Thanks.

**Comment by SmetDenis** [comment]
All these features available in the 3.x version. It is stable now.
Thanks.

**Comment by mapirelli** [comment]
Hi Denis, 
thanks for the new features, looks perfect.
I don't found the method to get the modified image in string format, must i use the base64 function and then convert the result ?

**Comment by SmetDenis** [comment]
Hi,

You can use `$string = $image->getBase64(<FORMAT>)`
or `$image->getImage()` to convert string manually.

May be you can sugget me some another method to convert it to string? May be with pull request?

Best regards, Denis.

**Comment by mapirelli** [comment]
Hi,

``php

    /**
     * Outputs image as binary string 
     *
     * @param null|string $format  If omitted or null - format of original file will be used, may be gif|jpg|png
     * @param int|null    $quality Output image quality in percents 0-100
     * @return string
     *
     * @throws Exception
     */
    public function getBase64($format = 'gif', $quality = null)
    {
        if (!$this->_image) {
            throw new Exception('Image resource not defined');
        }
        // Output the image
        ob_start();
        $mimetype  = $this->_renderImageByFormat($format, null, $quality);
        $imageData = ob_get_contents();
        ob_end_clean();
        return 'data:' . $mimetype . ';base64,' . base64_encode($imageData);
    }

`

**Comment by SmetDenis** [comment]
Hi mapirelli,

Try to use getBinary() from v3.0.2

**Comment by mapirelli** [comment]
Hi Denis, thank you very much.

**Comment by SmetDenis** [comment]
You are welcome :)
