### ISSUE TITLE
Background turn black in transparent png image

### ISSUE THREAD

**Issue by midhun1993** [JBZoo/Image#10]
After watermarking transparent background of png image turns black
any idea ?

**Comment by SmetDenis** [comment]
Hi,

Can you give me your png image ?

And see https://github.com/JBZoo/Image/issues/8

**Comment by midhun1993** [comment]
Hi..
here is the png : https://drive.google.com/open?id=0Bwq4DvGGbHVfM1Y3UHBxN1d5M0k
sorry for the late reply
