### ISSUE TITLE
Gaussian Blur more than 2 passes

### ISSUE THREAD

**Issue by franciscoprado** [JBZoo/Image#13]
Hello,

I think this library is very useful, it helped me working with images.

I would to blur an image more than 2 passes. A heavy blur. I can do it calling the function more than one time:

$img = (new Image($source))
        ->addFilter('blur', Filter::BLUR_SEL)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->addFilter('smooth', -10)
        ->saveAs($destination);

But there's a overhead doing this. Is there any way to blur the image with more intensity with just one call?

I've tried shrinking and increasing and applying the blur, but I only have got a pixelate image.

Thanks in advance,

**Comment by SmetDenis** [comment]
Hi,

Try to save image after each filter

```php
for($i = 0; $i < 10; $i++) {
    (new Image($source))
        ->addFilter('blur', Filter::BLUR_GAUS, 2)
        ->save();
}
```

**Comment by franciscoprado** [comment]
Thank you @SmetDenis 

I've tried as suggested by you, but the result is very slow, too.

Please, maybe I have to consider again to work with imageconvolution (PHP native solution) ? I have  little experience working with images using PHP.

Regards,

**Comment by SmetDenis** [comment]
This is PHP native solution, not mine,
https://github.com/JBZoo/Image/blob/master/src/Filter.php#L109
http://php.net/manual/en/function.imagefilter.php

I'm sorry. I think it's slow gd filter.

**Comment by pan-tom** [comment]
Looking to the source we can see that there's a different order of arguments, so you have to call that method like this:

`->addFilter('blur', 2, Filter::BLUR_GAUS)`

See: [https://github.com/JBZoo/Image/blob/master/src/Filter.php#L99](https://github.com/JBZoo/Image/blob/master/src/Filter.php#L99)
