### ISSUE TITLE
Black box appears when trying to add an overlay

### ISSUE THREAD

**Issue by Coriou** [JBZoo/Image#7]
I'm having a very weird issue I really can't understand :

I am trying to add a watermark over an image. It works fine, except that it will add a black box constantly below my overlay image. Here's what the final results looks like : https://i.imgur.com/pfPHrWN.png

My base image : https://i.imgur.com/OtMY1o1.png
My watermark image : https://i.imgur.com/zbgtXzd.png

The images above are dummies for this issue reporting, but I have tried with a bunch of images (both base & overlay) and with JPG, PNG & GIF types...

My code is very basic :

```
$image = new JBZoo\Image\Image( $baseImagePath );
$image->overlay( $watermarkImagePath )->saveAs( $newImage );
```

As for my environment, I'm using `PHP 5.5.26` and `GD bundled (2.1.0 compatible)`

**Comment by SmetDenis** [comment]
Hi @Coriou 

I created test to check this issue
https://github.com/JBZoo/Image/blob/master/tests/IssuesTest.php#L25

Expected image
https://github.com/JBZoo/Image/blob/master/tests/expected/issue_7.png

And I used it on PHP 5.4 ... 7.0  Well... It works fine.
My general env for developing is PHP 5.6.17 GD 2.1.0
![image](https://cloud.githubusercontent.com/assets/1118678/15777550/6bc0c8f8-29ba-11e6-8576-7665da468622.png)

I'm sorry. I don't know how to repeat this bug.
Can you execute testIssue7 and check result?

Thanks.

**Comment by Coriou** [comment]
Hello @SmetDenis 

Thank you so much for looking into my issue, and for creating a test for me. Please don't apologize for not being to reproduce !!

I, on the other hand, but I generally don't use PHPUnit nor Composer (yeah, I know ...) and I can't figure out how to run the test you created for me.

I installed the latest dev version of `JBZoo/Image/` and also required `PHPUnit` via Composer in that same folder. No matter how I try to run it, I'm getting a `Fatal error: Class 'JBZoo\PHPUnit\PHPUnit' not found`

Would you mind telling how to run this test please :( ?

Thanks.

**Comment by SmetDenis** [comment]
Hi, 

Download last composer https://getcomposer.org/download/1.1.2/composer.phar
Create new dir and put `composer.phar` into this folder

Open terminal (console) for your folder and execute this command
```sh
mkdir /tmp/jbzoo-image
cd /tmp/jbzoo-image
php composer.phar create-project jbzoo/image:3.x-dev
```

And just run all tests
```sh
php composer.phar --working-dir=/tmp/jbzoo-image/image test
```
After that you can find images here `/tmp/jbzoo-image/image/build/images/*`
One of them is issue_7.png

Source images are here /tmp/jbzoo-image/image/tests/resources/issue-7/

Some screens
Start - http://llfl.ru/40p3mt
Installing - http://llfl.ru/zbatxo
After installing - http://llfl.ru/bzimge and http://llfl.ru/ef0572
Tests - http://llfl.ru/d2kutk
Result - http://llfl.ru/06bxga

It's really easy that seems ;)

**Comment by Coriou** [comment]
[![Composer not found](https://i.imgur.com/i6V6C0j.png)](https://i.imgur.com/i6V6C0j.png)

Ahahah ?

I already had `composer` in my path. So what I did is :

```
composer self-update
mkdir /tmp/jbzoo-image/ && cd "$_"
composer create-project jbzoo/image:3.x-dev
composer --working-dir=/tmp/jbzoo-image/image test
```

And that's it ... First thing `composer` tries to do is to validate composer.json and it just fails straight away.

I don't have a "special" environment either. What is wrong with me here :(

**Comment by SmetDenis** [comment]
Hi,

Usually composer and phpunit are global system tool.



Try to run
```sh
cd /tmp/jbzoo-image/image
php ./vendor/phpunit/phpunit/phpunit --configuration ./phpunit.xml.dist
```
or
```sh
cd /tmp/jbzoo-image/image
php composer.phar --working-dir=/tmp/jbzoo-image/image phpunit
```
or
```sh
cd /tmp/jbzoo-image/image
phpunit
```

**Comment by Coriou** [comment]
Oh wait.. I'm so sorry, because I just wasted your time !!

I was running an old version of `JBZoo/Image` (that's what happens when you don't use `composer`) ! I just bumped to latest stable version and the problem is gone ...

I'm really sorry for all that time for nothing, and I really thank you for that outstanding support your provided !

**Comment by SmetDenis** [comment]
Don't worry :)
I'm glad that you are using my project.

Have a nice day

Best regards, Denis.
