### ISSUE TITLE
Black background at png images.

### ISSUE THREAD

**Issue by stgalkin** [JBZoo/Image#8]
Hi. I didn't find any solution or problems like mine, so i try ask here. 
I try to save an image preview with some height and width, but then i saved it, the image have black background if the background was transparent. Here the code:
` $img = (new Image(base_path() .'/public/img/products/'.$new_filename));
            if ($img->getHeight() != $img->getWidth()) {
                if ($img->getWidth() < 175) {
                    $img->fitToWidth($img->getWidth());
                } else {
                    $img->fitToWidth(175);
                }
            } else {
                $img->bestFit(175, 175);
            }
            $img->saveAs(base_path() .'/public/img/products/preview/'.$new_filename);`
Here the picture's:
[with black](https://i.gyazo.com/b8ed326401a5280c02bdc91f75fa11d6.png)
[original](https://i.gyazo.com/a7b7d481c8b42e1bf4893625734f1556.png)

UPD: theversion is "jbzoo/image": "^3.0",

**Comment by SmetDenis** [comment]
Hi @stgalkin 

Please, can you attach your original image with transparent background ?
I opened  your original image by link but it's white

https://cloud.githubusercontent.com/assets/1118678/15892209/bb679a80-2da2-11e6-86a3-1a88405ce0ba.png

Tell me PHP and GD version.

Thanks.

**Comment by stgalkin** [comment]
Sorry, it was a screenshot. The original picture i have taken from  [here](http://vignette4.wikia.nocookie.net/robber-penguin-agency/images/6/6e/Small-mario.png/revision/latest?cb=20150107080404) . It is with all png images which i try to resize. I take the mario pic for example.
GD bundled (2.1.0 compatible) // PHP Version 5.6.3
OpenServer 5.2.2

**Comment by SmetDenis** [comment]
Thanks!

I fixed it. Please try to use jbzoo/image:3.x-dev version (or dev-master).

**Comment by stgalkin** [comment]
Many thanks to you. Now all works correctly.
Thanks for fast fix&reply. You make great things.
